const $ = (selector) => document.querySelector(selector);
const keys = { users: 'nj_users', session: 'nj_session', drivers: 'nj_drivers', vehicles: 'nj_vehicles' };
const get = (key) => JSON.parse(localStorage.getItem(key) || '[]');
const api = async (path, options = {}) => { const response = await fetch('/api/' + path, { headers: { 'Content-Type': 'application/json' }, ...options }); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Não foi possível concluir a operação.'); return body; };
const set = (key, value) => { const previous = get(key); localStorage.setItem(key, JSON.stringify(value)); const resource = key === keys.drivers ? 'drivers' : key === keys.vehicles ? 'vehicles' : null; if (!resource) return; const changed = value.find(item => { const old = previous.find(row => row.id === item.id); return !old || JSON.stringify(old) !== JSON.stringify(item); }); if (changed) api(`${resource}${previous.some(row => row.id === changed.id) ? '/' + changed.id : ''}`, { method: previous.some(row => row.id === changed.id) ? 'PUT' : 'POST', body: JSON.stringify(changed) }).catch(error => console.error(error.message)); };
const authView = $('#auth-view'), appView = $('#app-view');
let isRegister = false, currentView = 'drivers', modalType = 'driver';

const statusClass = (status) => status === 'Ativo' || status === 'Em operação' ? 'active' : status === 'Pendente' || status === 'Manutenção' ? 'pending' : 'inactive';
const label = (tag, content, full = false) => `<label class="${full ? 'full-width' : ''}">${tag}${content}</label>`;
function formatCpf(value) { return value.replace(/\D/g, '').slice(0, 11).replace(/(\d{3})(\d)/, '$1.$2').replace(/(\d{3})(\d)/, '$1.$2').replace(/(\d{3})(\d{1,2})$/, '$1-$2'); }
function formatPlate(value) { return value.toUpperCase().replace(/[^A-Z0-9]/g, '').slice(0, 7).replace(/^([A-Z]{3})([0-9A-Z])/, '$1-$2'); }

function renderAuth() { $('#auth-title').textContent = isRegister ? 'Crie sua conta' : 'Acesse sua conta'; $('#auth-subtitle').textContent = isRegister ? 'Cadastre-se para começar a usar o sistema.' : 'Entre para continuar na gestão NJTransportes.'; $('#login-form').classList.toggle('hidden', isRegister); $('#register-form').classList.toggle('hidden', !isRegister); $('#auth-switch').innerHTML = isRegister ? 'Já possui uma conta? <button type="button" data-auth-mode="login">Entrar</button>' : 'Ainda não tem uma conta? <button type="button" data-auth-mode="register">Cadastre-se</button>'; }
document.addEventListener('click', (event) => { if (event.target.dataset.authMode) { isRegister = event.target.dataset.authMode === 'register'; renderAuth(); } });
$('#register-form').addEventListener('submit', async (event) => { event.preventDefault(); try { const user = await api('auth/register', { method: 'POST', body: JSON.stringify({ name: $('#register-name').value, email: $('#register-email').value, password: $('#register-password').value }) }); localStorage.setItem(keys.session, JSON.stringify(user)); showApp(); } catch (error) { $('#register-error').textContent = error.message; } });
$('#login-form').addEventListener('submit', async (event) => { event.preventDefault(); try { const user = await api('auth/login', { method: 'POST', body: JSON.stringify({ email: $('#login-email').value, password: $('#login-password').value }) }); localStorage.setItem(keys.session, JSON.stringify(user)); showApp(); } catch (error) { $('#login-error').textContent = error.message; } });
async function showApp() { const session = JSON.parse(localStorage.getItem(keys.session) || 'null'); if (!session) return; try { const [drivers, vehicles] = await Promise.all([api('drivers'), api('vehicles')]); localStorage.setItem(keys.drivers, JSON.stringify(drivers)); localStorage.setItem(keys.vehicles, JSON.stringify(vehicles)); } catch (error) { console.error(error.message); } authView.classList.add('hidden'); appView.classList.remove('hidden'); $('#user-name').textContent = session.name; $('#avatar').textContent = session.name.charAt(0).toUpperCase(); switchView(currentView); }
$('#logout-button').addEventListener('click', () => { localStorage.removeItem(keys.session); appView.classList.add('hidden'); authView.classList.remove('hidden'); });

function renderDrivers() { const all = get(keys.drivers), query = $('#driver-search').value.toLowerCase(), list = all.filter(item => `${item.name} ${item.cpf}`.toLowerCase().includes(query)); $('#total-drivers').textContent = all.length; $('#active-drivers').textContent = all.filter(item => item.status === 'Ativo').length; $('#pending-drivers').textContent = all.filter(item => item.status === 'Pendente').length; $('#drivers-table').innerHTML = list.map(item => `<tr><td class="driver-cell">${item.name}</td><td>${item.cpf}</td><td>${item.cnh}</td><td>${item.category}</td><td><span class="badge ${statusClass(item.status)}">${item.status}</span></td><td><button class="table-action" data-edit-driver="${item.id}">Editar</button></td></tr>`).join(''); $('#drivers-empty').classList.toggle('hidden', all.length > 0); }
function renderVehicles() { const all = get(keys.vehicles), query = $('#vehicle-search').value.toLowerCase(), list = all.filter(item => `${item.plate} ${item.model}`.toLowerCase().includes(query)); $('#total-vehicles').textContent = all.length; $('#active-vehicles').textContent = all.filter(item => item.status === 'Em operação').length; $('#maintenance-vehicles').textContent = all.filter(item => item.status === 'Manutenção').length; $('#vehicles-table').innerHTML = list.map(item => `<tr><td class="driver-cell">${item.plate}</td><td>${item.model}</td><td>${item.type}</td><td>${item.year}</td><td><span class="badge ${statusClass(item.status)}">${item.status}</span></td><td><button class="table-action" data-edit-vehicle="${item.id}">Editar</button></td></tr>`).join(''); $('#vehicles-empty').classList.toggle('hidden', all.length > 0); }
function switchView(view) { currentView = view; const vehicles = view === 'vehicles'; $('#drivers-view').classList.toggle('hidden', vehicles); $('#vehicles-view').classList.toggle('hidden', !vehicles); $('#page-title').textContent = vehicles ? 'Veículos' : 'Motoristas'; $('#new-item-button').textContent = vehicles ? '+ Novo veículo' : '+ Novo motorista'; document.querySelectorAll('[data-view]').forEach(link => link.classList.toggle('active', link.dataset.view === view)); vehicles ? renderVehicles() : renderDrivers(); }
document.querySelectorAll('[data-view]').forEach(link => link.addEventListener('click', event => { event.preventDefault(); switchView(link.dataset.view); }));
$('#driver-search').addEventListener('input', renderDrivers); $('#vehicle-search').addEventListener('input', renderVehicles);

function fields(type, item = {}) { const option = (values, selected) => values.map(value => '<option ' + (selected === value ? 'selected' : '') + '>' + value + '</option>').join(''); if (type === 'vehicle') return [label('Placa<input id="plate" required maxlength="8" placeholder="ABC-1D23" value="' + (item.plate || '') + '" />'), label('Marca e modelo<input id="model" required placeholder="Ex.: Volvo FH 540" value="' + (item.model || '') + '" />'), label('Tipo<select id="type" required><option value="">Selecione</option>' + option(['Caminhão', 'Cavalo mecânico', 'Carreta', 'VUC', 'Utilitário'], item.type) + '</select>'), label('Ano<input id="year" type="number" required min="1950" max="2100" placeholder="2024" value="' + (item.year || '') + '" />'), label('RENAVAM<input id="renavam" placeholder="Número do RENAVAM" value="' + (item.renavam || '') + '" />'), label('Status<select id="status" required>' + option(['Em operação', 'Manutenção', 'Inativo'], item.status || 'Em operação') + '</select>')].join(''); return [label('Nome completo<input id="name" required placeholder="Nome do motorista" value="' + (item.name || '') + '" />'), label('CPF<input id="cpf" required maxlength="14" placeholder="000.000.000-00" value="' + (item.cpf || '') + '" />'), label('CNH<input id="cnh" required placeholder="Número da CNH" value="' + (item.cnh || '') + '" />'), label('Categoria<select id="category" required><option value="">Selecione</option>' + option(['A', 'B', 'C', 'D', 'E', 'AB', 'AC', 'AD', 'AE'], item.category) + '</select>'), label('Validade da CNH<input id="expiry" type="date" required value="' + (item.expiry || '') + '" />'), label('Status<select id="status" required>' + option(['Ativo', 'Pendente', 'Inativo'], item.status || 'Ativo') + '</select>'), label('Telefone<input id="phone" placeholder="(00) 00000-0000" value="' + (item.phone || '') + '" />', true)].join(''); }
function openModal(type, item) { modalType = type; $('#modal-title').textContent = `${item ? 'Editar' : 'Novo'} ${type === 'vehicle' ? 'veículo' : 'motorista'}`; $('#modal-fields').innerHTML = `<input type="hidden" id="record-id" value="${item?.id || ''}" />${fields(type, item)}`; $('#modal-backdrop').classList.remove('hidden'); }
function closeModal() { $('#modal-backdrop').classList.add('hidden'); $('#record-error').textContent = ''; }
$('#new-item-button').addEventListener('click', () => openModal(currentView === 'vehicles' ? 'vehicle' : 'driver')); document.addEventListener('click', event => { if (event.target.dataset.new) openModal(event.target.dataset.new); if (event.target.dataset.editDriver) openModal('driver', get(keys.drivers).find(item => item.id === event.target.dataset.editDriver)); if (event.target.dataset.editVehicle) openModal('vehicle', get(keys.vehicles).find(item => item.id === event.target.dataset.editVehicle)); }); $('#close-modal').addEventListener('click', closeModal); $('#cancel-modal').addEventListener('click', closeModal); $('#modal-backdrop').addEventListener('click', event => { if (event.target === $('#modal-backdrop')) closeModal(); });
$('#record-form').addEventListener('input', event => { if (event.target.id === 'cpf') event.target.value = formatCpf(event.target.value); if (event.target.id === 'plate') event.target.value = formatPlate(event.target.value); });
$('#record-form').addEventListener('submit', event => { event.preventDefault(); const id = $('#record-id').value, vehicle = modalType === 'vehicle', storeKey = vehicle ? keys.vehicles : keys.drivers, all = get(storeKey); const data = vehicle ? { id: id || crypto.randomUUID(), plate: $('#plate').value, model: $('#model').value.trim(), type: $('#type').value, year: $('#year').value, renavam: $('#renavam').value.trim(), status: $('#status').value } : { id: id || crypto.randomUUID(), name: $('#name').value.trim(), cpf: $('#cpf').value, cnh: $('#cnh').value.trim(), category: $('#category').value, expiry: $('#expiry').value, status: $('#status').value, phone: $('#phone').value.trim() }; const duplicate = all.find(item => item[vehicle ? 'plate' : 'cpf'] === data[vehicle ? 'plate' : 'cpf'] && item.id !== id); if (duplicate) return $('#record-error').textContent = vehicle ? 'Já existe um veículo com esta placa.' : 'Já existe um motorista com este CPF.'; set(storeKey, id ? all.map(item => item.id === id ? data : item) : [...all, data]); closeModal(); vehicle ? renderVehicles() : renderDrivers(); });
async function showClients() { $('#drivers-view').classList.add('hidden'); $('#vehicles-view').classList.add('hidden'); $('#clients-view').classList.remove('hidden'); $('#page-title').textContent = 'Clientes'; $('#new-item-button').textContent = '+ Novo cliente'; const clients = await api('clients'); $('#clients-table').innerHTML = clients.map(c => `<tr><td class="driver-cell">${c.name}</td><td>${c.address}, ${c.number || 's/n'}</td><td>${c.city}/${c.state}</td><td>${c.phone || '-'}</td><td></td></tr>`).join(''); $('#clients-empty').classList.toggle('hidden', clients.length > 0); }
document.querySelector('[data-view="clients"]').addEventListener('click', event => { event.preventDefault(); showClients(); });
document.addEventListener('click', async event => { if (event.target.dataset.new !== 'client') return; const name = prompt('Nome do cliente:'); if (!name) return; const address = prompt('Rua/Avenida:'); const number = prompt('Número:'); const city = prompt('Cidade:'); const state = prompt('UF:'); if (!address || !city || !state) return alert('Endereço, cidade e UF são obrigatórios.'); await api('clients', { method: 'POST', body: JSON.stringify({ name, address, number, city, state, status: 'Ativo' }) }); showClients(); });
$('#sidebar-toggle').addEventListener('click', () => $('#sidebar').classList.toggle('collapsed')); $('#mobile-menu').addEventListener('click', () => $('#sidebar').classList.toggle('open')); renderAuth(); showApp();
